#Tech-Ken Match History
#Sun May 17 19:13:22 CST 2026
match0=Heihachi Mishima|Manny Pacquiao|Heihachi Mishima|2026-05-11 21\:14\:27
match1=Heihachi Mishima|Reptile|Heihachi Mishima|2026-05-11 21\:18\:45
match10=Devil Jin|Manny Pacquiao|Devil Jin|2026-05-17 19\:08\:38
match11=Devil Jin|Devil Jin|Devil Jin|2026-05-17 19\:13\:22
match2=Heihachi Mishima|Tiger|Heihachi Mishima|2026-05-13 21\:46\:52
match3=Manny Pacquiao|Scorpion|Scorpion|2026-05-13 22\:21\:59
match4=Heihachi Mishima|Tiger|Heihachi Mishima|2026-05-13 22\:22\:29
match5=Heihachi Mishima|Scorpion|Heihachi Mishima|2026-05-17 17\:22\:56
match6=Manny Pacquiao|Devil Jin|Devil Jin|2026-05-17 18\:32\:35
match7=Tiger|Johnny Cage|Tiger|2026-05-17 18\:35\:26
match8=Devil Jin|Reptile|Devil Jin|2026-05-17 19\:04\:06
match9=Devil Jin|Scorpion|Devil Jin|2026-05-17 19\:07\:10
