#Tech-Ken Match History
#Wed May 13 22:22:29 PST 2026
match0=Heihachi Mishima|Manny Pacquiao|Heihachi Mishima|2026-05-11 21\:14\:27
match1=Heihachi Mishima|Reptile|Heihachi Mishima|2026-05-11 21\:18\:45
match2=Heihachi Mishima|Tiger|Heihachi Mishima|2026-05-13 21\:46\:52
match3=Manny Pacquiao|Scorpion|Scorpion|2026-05-13 22\:21\:59
match4=Heihachi Mishima|Tiger|Heihachi Mishima|2026-05-13 22\:22\:29
